version: '3'
services:
    db:
        image: postgres:14
        environment:
            POSTGRES_USER: auth_user
            POSTGRES_PASSWORD: auth_pass
            POSTGRES_DB: auth_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: